name: CEGA
favicon: null
layout_spectrum: 0.08783891052007675
typography_spectrum: 0.704075827030465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.4251013046596199
  lightness: 0.6494193270336837
  saturation: 0.052492705173790455
  rhythmicContrast: 0.5775977612938732
purpose: []
